Add PHP config files for UDB3 silex deployment
cultuurnet/puppet-deployment pull request #9
Opened 2022-09-27 09:45 UTC by willaerk

## Added

PHP config files in addition to the existing YAML based config files

--- 
Ticket: https://jira.uitdatabank.be/browse/III-3837

2022-09-27 11:05 UTC, JonasVHG requested changes
We also replaced the yaml files for external_id, excluded_labels & terms_mapping.
It would be best to also include them.

2022-09-27 11:05 UTC, JonasVHG commented on manifests/udb3/silex.pp
>    $externalid_place_mapping_source,
@willaerk , maybe best to also add the other php-replacements for the YAML Files (externa_id_mapping, terms_mappings, excluded_labels)

2022-09-27 13:41 UTC, willaerk commented on manifests/udb3/silex.pp
>    $externalid_place_mapping_source,
Yes, indeed. I have added configuration for all files now

2022-09-28 10:29 UTC, bertramakers approved these changes

2022-09-28 10:37 UTC, JonasVHG approved these changes

2022-09-29 11:17 UTC, merged